name: 🚀 Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'


jobs:
  quality:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependecies
        run: npm ci

      - name: Typescript to Javascript
        run: npm run build

      - name: Run Tests
        run: npm test
        
        
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [quality]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependecies
        run: npm ci

      - name: Typescript to Javascript
        run: npm run build

      - name: Create Release
        run: npm run semantic-release
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}